name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        sudo apt-get update
        sudo apt-get -y install libx11-dev libxft-dev libxft2
        make
      working-directory: src
